title: iRadio docs
description: huh?
theme: just-the-docs

url: https://docs.eveee00.xyz

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark

favicon_ico: "/assets/favicon.ico"
